
import Foundation
import SpriteKit

class EFObjFishData {
    
    class func fish1() -> Array<String> {
        var arr = Array<String>()
        arr.append("Fish1_1.png")
        arr.append("Fish1_2.png")
        arr.append("Fish1_3.png")
        arr.append("Fish1_4.png")
        arr.append("Fish1_5.png")
        arr.append("Fish1_6.png")
        arr.append("Fish1_7.png")
        arr.append("Fish1_8.png")
        arr.append("Fish1_9.png")
        arr.append("Fish1_10.png")
        arr.append("Fish1_11.png")
        arr.append("Fish1_12.png")
        arr.append("Fish1_13.png")
        arr.append("Fish1_14.png")
        arr.append("Fish1_15.png")
        arr.append("Fish1_16.png")
        arr.append("Fish1_17.png")
        arr.append("Fish1_18.png")
        arr.append("Fish1_19.png")
        arr.append("Fish1_20.png")
        arr.append("Fish1_21.png")
        arr.append("Fish1_22.png")
        arr.append("Fish1_23.png")
        arr.append("Fish1_24.png")
        return arr
    }
    
    class func fish2() -> Array<String> {
        var arr = Array<String>()
        arr.append("Fish2_1.png")
        arr.append("Fish2_2.png")
        arr.append("Fish2_3.png")
        arr.append("Fish2_4.png")
        arr.append("Fish2_5.png")
        arr.append("Fish2_6.png")
        arr.append("Fish2_7.png")
        arr.append("Fish2_8.png")
        arr.append("Fish2_9.png")
        arr.append("Fish2_10.png")
        arr.append("Fish2_11.png")
        arr.append("Fish2_12.png")
        arr.append("Fish2_13.png")
        arr.append("Fish2_14.png")
        arr.append("Fish2_15.png")
        arr.append("Fish2_16.png")
        arr.append("Fish2_17.png")
        arr.append("Fish2_18.png")
        arr.append("Fish2_19.png")
        arr.append("Fish2_20.png")
        arr.append("Fish2_21.png")
        arr.append("Fish2_22.png")
        arr.append("Fish2_23.png")
        arr.append("Fish2_24.png")
        return arr
    }
    
    class func fish3() -> Array<String> {
        var arr = Array<String>()
        arr.append("Fish3_1.png")
        arr.append("Fish3_2.png")
        arr.append("Fish3_3.png")
        arr.append("Fish3_4.png")
        arr.append("Fish3_5.png")
        arr.append("Fish3_6.png")
        arr.append("Fish3_7.png")
        arr.append("Fish3_8.png")
        arr.append("Fish3_9.png")
        arr.append("Fish3_10.png")
        arr.append("Fish3_11.png")
        arr.append("Fish3_12.png")
        arr.append("Fish3_13.png")
        arr.append("Fish3_14.png")
        arr.append("Fish3_15.png")
        arr.append("Fish3_16.png")
        arr.append("Fish3_17.png")
        arr.append("Fish3_18.png")
        arr.append("Fish3_19.png")
        arr.append("Fish3_20.png")
        arr.append("Fish3_21.png")
        arr.append("Fish3_22.png")
        arr.append("Fish3_23.png")
        arr.append("Fish3_24.png")
        return arr
    }
    
    class func fish4() -> Array<String> {
        var arr = Array<String>()
        arr.append("Fish4_1.png")
        arr.append("Fish4_2.png")
        arr.append("Fish4_3.png")
        arr.append("Fish4_4.png")
        arr.append("Fish4_5.png")
        arr.append("Fish4_6.png")
        arr.append("Fish4_7.png")
        arr.append("Fish4_8.png")
        arr.append("Fish4_9.png")
        arr.append("Fish4_10.png")
        arr.append("Fish4_11.png")
        arr.append("Fish4_12.png")
        arr.append("Fish4_13.png")
        arr.append("Fish4_14.png")
        arr.append("Fish4_15.png")
        arr.append("Fish4_16.png")
        arr.append("Fish4_17.png")
        arr.append("Fish4_18.png")
        arr.append("Fish4_19.png")
        arr.append("Fish4_20.png")
        arr.append("Fish4_21.png")
        arr.append("Fish4_22.png")
        arr.append("Fish4_23.png")
        arr.append("Fish4_24.png")
        return arr
    }
    
    class func fish5() -> Array<String> {
        var arr = Array<String>()
        arr.append("Fish5_1.png")
        arr.append("Fish5_2.png")
        arr.append("Fish5_3.png")
        arr.append("Fish5_4.png")
        arr.append("Fish5_5.png")
        arr.append("Fish5_6.png")
        arr.append("Fish5_7.png")
        arr.append("Fish5_8.png")
        arr.append("Fish5_9.png")
        arr.append("Fish5_10.png")
        arr.append("Fish5_11.png")
        arr.append("Fish5_12.png")
        arr.append("Fish5_13.png")
        arr.append("Fish5_14.png")
        arr.append("Fish5_15.png")
        arr.append("Fish5_16.png")
        arr.append("Fish5_17.png")
        arr.append("Fish5_18.png")
        arr.append("Fish5_19.png")
        arr.append("Fish5_20.png")
        arr.append("Fish5_21.png")
        arr.append("Fish5_22.png")
        arr.append("Fish5_23.png")
        arr.append("Fish5_24.png")
        return arr
    }
    
    class func fish6() -> Array<String> {
        var arr = Array<String>()
        arr.append("Fish6_1.png")
        arr.append("Fish6_2.png")
        arr.append("Fish6_3.png")
        arr.append("Fish6_4.png")
        arr.append("Fish6_5.png")
        arr.append("Fish6_6.png")
        arr.append("Fish6_7.png")
        arr.append("Fish6_8.png")
        arr.append("Fish6_9.png")
        arr.append("Fish6_10.png")
        arr.append("Fish6_11.png")
        arr.append("Fish6_12.png")
        arr.append("Fish6_13.png")
        arr.append("Fish6_14.png")
        arr.append("Fish6_15.png")
        arr.append("Fish6_16.png")
        arr.append("Fish6_17.png")
        arr.append("Fish6_18.png")
        arr.append("Fish6_19.png")
        arr.append("Fish6_20.png")
        arr.append("Fish6_21.png")
        arr.append("Fish6_22.png")
        arr.append("Fish6_23.png")
        arr.append("Fish6_24.png")
        return arr
    }
    
    class func playerFish() -> Array<String> {
        var arr = Array<String>()
        arr.append("playFish1.png")
        arr.append("playFish2.png")
        arr.append("playFish3.png")
        arr.append("playFish4.png")
        arr.append("playFish5.png")
        arr.append("playFish6.png")
        arr.append("playFish7.png")
        arr.append("playFish8.png")
        arr.append("playFish9.png")
        arr.append("playFish10.png")
        arr.append("playFish11.png")
        arr.append("playFish12.png")
        arr.append("playFish13.png")
        arr.append("playFish14.png")
        arr.append("playFish15.png")
        arr.append("playFish16.png")
        arr.append("playFish17.png")
        arr.append("playFish18.png")
        arr.append("playFish19.png")
        arr.append("playFish20.png")
        arr.append("playFish21.png")
        arr.append("playFish22.png")
        arr.append("playFish23.png")
        arr.append("playFish24.png")
        return arr
    }
    
    class func playerBFish() -> Array<String> {
        var arr = Array<String>()
        arr.append("playBFish1.png")
        arr.append("playBFish2.png")
        arr.append("playBFish3.png")
        arr.append("playBFish4.png")
        arr.append("playBFish5.png")
        arr.append("playBFish6.png")
        arr.append("playBFish7.png")
        arr.append("playBFish8.png")
        arr.append("playBFish9.png")
        arr.append("playBFish10.png")
        arr.append("playBFish11.png")
        arr.append("playBFish12.png")
        arr.append("playBFish13.png")
        arr.append("playBFish14.png")
        arr.append("playBFish15.png")
        arr.append("playBFish16.png")
        arr.append("playBFish17.png")
        arr.append("playBFish18.png")
        arr.append("playBFish19.png")
        arr.append("playBFish20.png")
        arr.append("playBFish21.png")
        arr.append("playBFish22.png")
        arr.append("playBFish23.png")
        arr.append("playBFish24.png")
        return arr
    }
    
    class func playerMFish() -> Array<String> {
        var arr = Array<String>()
        arr.append("playMFish1.png")
        arr.append("playMFish2.png")
        arr.append("playMFish3.png")
        arr.append("playMFish4.png")
        arr.append("playMFish5.png")
        arr.append("playMFish6.png")
        arr.append("playMFish7.png")
        arr.append("playMFish8.png")
        arr.append("playMFish9.png")
        arr.append("playMFish10.png")
        arr.append("playMFish11.png")
        arr.append("playMFish12.png")
        arr.append("playMFish13.png")
        arr.append("playMFish14.png")
        arr.append("playMFish15.png")
        arr.append("playMFish16.png")
        arr.append("playMFish17.png")
        arr.append("playMFish18.png")
        arr.append("playMFish19.png")
        arr.append("playMFish20.png")
        arr.append("playMFish21.png")
        arr.append("playMFish22.png")
        arr.append("playMFish23.png")
        arr.append("playMFish24.png")
        return arr
    }
    
    class func jellyFish() -> Array<String> {
        var arr = Array<String>()
        arr.append("jellyfish1.png")
        arr.append("jellyfish2.png")
        arr.append("jellyfish3.png")
        arr.append("jellyfish4.png")
        arr.append("jellyfish5.png")
        arr.append("jellyfish6.png")
        arr.append("jellyfish7.png")
        arr.append("jellyfish8.png")
        arr.append("jellyfish9.png")
        arr.append("jellyfish10.png")
        arr.append("jellyfish11.png")
        arr.append("jellyfish12.png")
        arr.append("jellyfish13.png")
        arr.append("jellyfish14.png")
        arr.append("jellyfish15.png")
        arr.append("jellyfish16.png")
        arr.append("jellyfish17.png")
        arr.append("jellyfish18.png")
        arr.append("jellyfish19.png")
        arr.append("jellyfish20.png")
        arr.append("jellyfish21.png")
        arr.append("jellyfish22.png")
        arr.append("jellyfish23.png")
        arr.append("jellyfish24.png")
        return arr
    }
    
}
