
import Foundation
import SpriteKit

class EFObjFishData {
    
    class func fish1() -> Array<String> {
        var arr = Array<String>()
        arr.append("Fish1_1")
        arr.append("Fish1_2")
        arr.append("Fish1_3")
        arr.append("Fish1_4")
        arr.append("Fish1_5")
        arr.append("Fish1_6")
        arr.append("Fish1_7")
        arr.append("Fish1_8")
        arr.append("Fish1_9")
        arr.append("Fish1_10")
        arr.append("Fish1_11")
        arr.append("Fish1_12")
        arr.append("Fish1_13")
        arr.append("Fish1_14")
        arr.append("Fish1_15")
        arr.append("Fish1_16")
        arr.append("Fish1_17")
        arr.append("Fish1_18")
        arr.append("Fish1_19")
        arr.append("Fish1_20")
        arr.append("Fish1_21")
        arr.append("Fish1_22")
        arr.append("Fish1_23")
        arr.append("Fish1_24")
        return arr
    }
    
    class func fish2() -> Array<String> {
        var arr = Array<String>()
        arr.append("Fish2_1")
        arr.append("Fish2_2")
        arr.append("Fish2_3")
        arr.append("Fish2_4")
        arr.append("Fish2_5")
        arr.append("Fish2_6")
        arr.append("Fish2_7")
        arr.append("Fish2_8")
        arr.append("Fish2_9")
        arr.append("Fish2_10")
        arr.append("Fish2_11")
        arr.append("Fish2_12")
        arr.append("Fish2_13")
        arr.append("Fish2_14")
        arr.append("Fish2_15")
        arr.append("Fish2_16")
        arr.append("Fish2_17")
        arr.append("Fish2_18")
        arr.append("Fish2_19")
        arr.append("Fish2_20")
        arr.append("Fish2_21")
        arr.append("Fish2_22")
        arr.append("Fish2_23")
        arr.append("Fish2_24")
        return arr
    }
    
    class func fish3() -> Array<String> {
        var arr = Array<String>()
        arr.append("Fish3_1")
        arr.append("Fish3_2")
        arr.append("Fish3_3")
        arr.append("Fish3_4")
        arr.append("Fish3_5")
        arr.append("Fish3_6")
        arr.append("Fish3_7")
        arr.append("Fish3_8")
        arr.append("Fish3_9")
        arr.append("Fish3_10")
        arr.append("Fish3_11")
        arr.append("Fish3_12")
        arr.append("Fish3_13")
        arr.append("Fish3_14")
        arr.append("Fish3_15")
        arr.append("Fish3_16")
        arr.append("Fish3_17")
        arr.append("Fish3_18")
        arr.append("Fish3_19")
        arr.append("Fish3_20")
        arr.append("Fish3_21")
        arr.append("Fish3_22")
        arr.append("Fish3_23")
        arr.append("Fish3_24")
        return arr
    }
    
    class func fish4() -> Array<String> {
        var arr = Array<String>()
        arr.append("Fish4_1")
        arr.append("Fish4_2")
        arr.append("Fish4_3")
        arr.append("Fish4_4")
        arr.append("Fish4_5")
        arr.append("Fish4_6")
        arr.append("Fish4_7")
        arr.append("Fish4_8")
        arr.append("Fish4_9")
        arr.append("Fish4_10")
        arr.append("Fish4_11")
        arr.append("Fish4_12")
        arr.append("Fish4_13")
        arr.append("Fish4_14")
        arr.append("Fish4_15")
        arr.append("Fish4_16")
        arr.append("Fish4_17")
        arr.append("Fish4_18")
        arr.append("Fish4_19")
        arr.append("Fish4_20")
        arr.append("Fish4_21")
        arr.append("Fish4_22")
        arr.append("Fish4_23")
        arr.append("Fish4_24")
        return arr
    }
    
    class func fish5() -> Array<String> {
        var arr = Array<String>()
        arr.append("Fish5_1")
        arr.append("Fish5_2")
        arr.append("Fish5_3")
        arr.append("Fish5_4")
        arr.append("Fish5_5")
        arr.append("Fish5_6")
        arr.append("Fish5_7")
        arr.append("Fish5_8")
        arr.append("Fish5_9")
        arr.append("Fish5_10")
        arr.append("Fish5_11")
        arr.append("Fish5_12")
        arr.append("Fish5_13")
        arr.append("Fish5_14")
        arr.append("Fish5_15")
        arr.append("Fish5_16")
        arr.append("Fish5_17")
        arr.append("Fish5_18")
        arr.append("Fish5_19")
        arr.append("Fish5_20")
        arr.append("Fish5_21")
        arr.append("Fish5_22")
        arr.append("Fish5_23")
        arr.append("Fish5_24")
        return arr
    }
    
    class func fish6() -> Array<String> {
        var arr = Array<String>()
        arr.append("Fish6_1")
        arr.append("Fish6_2")
        arr.append("Fish6_3")
        arr.append("Fish6_4")
        arr.append("Fish6_5")
        arr.append("Fish6_6")
        arr.append("Fish6_7")
        arr.append("Fish6_8")
        arr.append("Fish6_9")
        arr.append("Fish6_10")
        arr.append("Fish6_11")
        arr.append("Fish6_12")
        arr.append("Fish6_13")
        arr.append("Fish6_14")
        arr.append("Fish6_15")
        arr.append("Fish6_16")
        arr.append("Fish6_17")
        arr.append("Fish6_18")
        arr.append("Fish6_19")
        arr.append("Fish6_20")
        arr.append("Fish6_21")
        arr.append("Fish6_22")
        arr.append("Fish6_23")
        arr.append("Fish6_24")
        return arr
    }
    
    class func playerFish() -> Array<String> {
        var arr = Array<String>()
        arr.append("playerFish1")
        arr.append("playerFish2")
        arr.append("playerFish3")
        arr.append("playerFish4")
        arr.append("playerFish5")
        arr.append("playerFish6")
        arr.append("playerFish7")
        arr.append("playerFish8")
        arr.append("playerFish9")
        arr.append("playerFish10")
        arr.append("playerFish11")
        arr.append("playerFish12")
        arr.append("playerFish13")
        arr.append("playerFish14")
        arr.append("playerFish15")
        arr.append("playerFish16")
        arr.append("playerFish17")
        arr.append("playerFish18")
        arr.append("playerFish19")
        arr.append("playerFish20")
        arr.append("playerFish21")
        arr.append("playerFish22")
        arr.append("playerFish23")
        arr.append("playerFish24")
        return arr
    }
    
    class func playerBFish() -> Array<String> {
        var arr = Array<String>()
        arr.append("playerBFish1")
        arr.append("playerBFish2")
        arr.append("playerBFish3")
        arr.append("playerBFish4")
        arr.append("playerBFish5")
        arr.append("playerBFish6")
        arr.append("playerBFish7")
        arr.append("playerBFish8")
        arr.append("playerBFish9")
        arr.append("playerBFish10")
        arr.append("playerBFish11")
        arr.append("playerBFish12")
        arr.append("playerBFish13")
        arr.append("playerBFish14")
        arr.append("playerBFish15")
        arr.append("playerBFish16")
        arr.append("playerBFish17")
        arr.append("playerBFish18")
        arr.append("playerBFish19")
        arr.append("playerBFish20")
        arr.append("playerBFish21")
        arr.append("playerBFish22")
        arr.append("playerBFish23")
        arr.append("playerBFish24")
        return arr
    }
    
    class func playerMFish() -> Array<String> {
        var arr = Array<String>()
        arr.append("playerMFish1")
        arr.append("playerMFish2")
        arr.append("playerMFish3")
        arr.append("playerMFish4")
        arr.append("playerMFish5")
        arr.append("playerMFish6")
        arr.append("playerMFish7")
        arr.append("playerMFish8")
        arr.append("playerMFish9")
        arr.append("playerMFish10")
        arr.append("playerMFish11")
        arr.append("playerMFish12")
        arr.append("playerMFish13")
        arr.append("playerMFish14")
        arr.append("playerMFish15")
        arr.append("playerMFish16")
        arr.append("playerMFish17")
        arr.append("playerMFish18")
        arr.append("playerMFish19")
        arr.append("playerMFish20")
        arr.append("playerMFish21")
        arr.append("playerMFish22")
        arr.append("playerMFish23")
        arr.append("playerMFish24")
        return arr
    }
    
    class func jellyFish() -> Array<String> {
        var arr = Array<String>()
        arr.append("jellyfish1")
        arr.append("jellyfish2")
        arr.append("jellyfish3")
        arr.append("jellyfish4")
        arr.append("jellyfish5")
        arr.append("jellyfish6")
        arr.append("jellyfish7")
        arr.append("jellyfish8")
        arr.append("jellyfish9")
        arr.append("jellyfish10")
        arr.append("jellyfish11")
        arr.append("jellyfish12")
        arr.append("jellyfish13")
        arr.append("jellyfish14")
        arr.append("jellyfish15")
        arr.append("jellyfish16")
        arr.append("jellyfish17")
        arr.append("jellyfish18")
        arr.append("jellyfish19")
        arr.append("jellyfish20")
        arr.append("jellyfish21")
        arr.append("jellyfish22")
        arr.append("jellyfish23")
        arr.append("jellyfish24")
        return arr
    }
    
}
