
import Foundation
import SpriteKit

class EFObjFishData {
    
    class func fish1() -> Array<String> {
        var arr = Array<String>()
        arr.append("Fishall/Fish1_1.png")
        arr.append("Fishall/Fish1_2.png")
        arr.append("Fishall/Fish1_3.png")
        arr.append("Fishall/Fish1_4.png")
        arr.append("Fishall/Fish1_5.png")
        arr.append("Fishall/Fish1_6.png")
        arr.append("Fishall/Fish1_7.png")
        arr.append("Fishall/Fish1_8.png")
        arr.append("Fishall/Fish1_9.png")
        arr.append("Fishall/Fish1_10.png")
        arr.append("Fishall/Fish1_11.png")
        arr.append("Fishall/Fish1_12.png")
        arr.append("Fishall/Fish1_13.png")
        arr.append("Fishall/Fish1_14.png")
        arr.append("Fishall/Fish1_15.png")
        arr.append("Fishall/Fish1_16.png")
        arr.append("Fishall/Fish1_17.png")
        arr.append("Fishall/Fish1_18.png")
        arr.append("Fishall/Fish1_19.png")
        arr.append("Fishall/Fish1_20.png")
        arr.append("Fishall/Fish1_21.png")
        arr.append("Fishall/Fish1_22.png")
        arr.append("Fishall/Fish1_23.png")
        arr.append("Fishall/Fish1_24.png")
        return arr
    }
    
    class func fish2() -> Array<String> {
        var arr = Array<String>()
        arr.append("Fishall/Fish2_1.png")
        arr.append("Fishall/Fish2_2.png")
        arr.append("Fishall/Fish2_3.png")
        arr.append("Fishall/Fish2_4.png")
        arr.append("Fishall/Fish2_5.png")
        arr.append("Fishall/Fish2_6.png")
        arr.append("Fishall/Fish2_7.png")
        arr.append("Fishall/Fish2_8.png")
        arr.append("Fishall/Fish2_9.png")
        arr.append("Fishall/Fish2_10.png")
        arr.append("Fishall/Fish2_11.png")
        arr.append("Fishall/Fish2_12.png")
        arr.append("Fishall/Fish2_13.png")
        arr.append("Fishall/Fish2_14.png")
        arr.append("Fishall/Fish2_15.png")
        arr.append("Fishall/Fish2_16.png")
        arr.append("Fishall/Fish2_17.png")
        arr.append("Fishall/Fish2_18.png")
        arr.append("Fishall/Fish2_19.png")
        arr.append("Fishall/Fish2_20.png")
        arr.append("Fishall/Fish2_21.png")
        arr.append("Fishall/Fish2_22.png")
        arr.append("Fishall/Fish2_23.png")
        arr.append("Fishall/Fish2_24.png")
        return arr
    }
    
    class func fish3() -> Array<String> {
        var arr = Array<String>()
        arr.append("Fishall/Fish3_1.png")
        arr.append("Fishall/Fish3_2.png")
        arr.append("Fishall/Fish3_3.png")
        arr.append("Fishall/Fish3_4.png")
        arr.append("Fishall/Fish3_5.png")
        arr.append("Fishall/Fish3_6.png")
        arr.append("Fishall/Fish3_7.png")
        arr.append("Fishall/Fish3_8.png")
        arr.append("Fishall/Fish3_9.png")
        arr.append("Fishall/Fish3_10.png")
        arr.append("Fishall/Fish3_11.png")
        arr.append("Fishall/Fish3_12.png")
        arr.append("Fishall/Fish3_13.png")
        arr.append("Fishall/Fish3_14.png")
        arr.append("Fishall/Fish3_15.png")
        arr.append("Fishall/Fish3_16.png")
        arr.append("Fishall/Fish3_17.png")
        arr.append("Fishall/Fish3_18.png")
        arr.append("Fishall/Fish3_19.png")
        arr.append("Fishall/Fish3_20.png")
        arr.append("Fishall/Fish3_21.png")
        arr.append("Fishall/Fish3_22.png")
        arr.append("Fishall/Fish3_23.png")
        arr.append("Fishall/Fish3_24.png")
        return arr
    }
    
    class func fish4() -> Array<String> {
        var arr = Array<String>()
        arr.append("Fishall/Fish4_1.png")
        arr.append("Fishall/Fish4_2.png")
        arr.append("Fishall/Fish4_3.png")
        arr.append("Fishall/Fish4_4.png")
        arr.append("Fishall/Fish4_5.png")
        arr.append("Fishall/Fish4_6.png")
        arr.append("Fishall/Fish4_7.png")
        arr.append("Fishall/Fish4_8.png")
        arr.append("Fishall/Fish4_9.png")
        arr.append("Fishall/Fish4_10.png")
        arr.append("Fishall/Fish4_11.png")
        arr.append("Fishall/Fish4_12.png")
        arr.append("Fishall/Fish4_13.png")
        arr.append("Fishall/Fish4_14.png")
        arr.append("Fishall/Fish4_15.png")
        arr.append("Fishall/Fish4_16.png")
        arr.append("Fishall/Fish4_17.png")
        arr.append("Fishall/Fish4_18.png")
        arr.append("Fishall/Fish4_19.png")
        arr.append("Fishall/Fish4_20.png")
        arr.append("Fishall/Fish4_21.png")
        arr.append("Fishall/Fish4_22.png")
        arr.append("Fishall/Fish4_23.png")
        arr.append("Fishall/Fish4_24.png")
        return arr
    }
    
    class func fish5() -> Array<String> {
        var arr = Array<String>()
        arr.append("Fishall/Fish5_1.png")
        arr.append("Fishall/Fish5_2.png")
        arr.append("Fishall/Fish5_3.png")
        arr.append("Fishall/Fish5_4.png")
        arr.append("Fishall/Fish5_5.png")
        arr.append("Fishall/Fish5_6.png")
        arr.append("Fishall/Fish5_7.png")
        arr.append("Fishall/Fish5_8.png")
        arr.append("Fishall/Fish5_9.png")
        arr.append("Fishall/Fish5_10.png")
        arr.append("Fishall/Fish5_11.png")
        arr.append("Fishall/Fish5_12.png")
        arr.append("Fishall/Fish5_13.png")
        arr.append("Fishall/Fish5_14.png")
        arr.append("Fishall/Fish5_15.png")
        arr.append("Fishall/Fish5_16.png")
        arr.append("Fishall/Fish5_17.png")
        arr.append("Fishall/Fish5_18.png")
        arr.append("Fishall/Fish5_19.png")
        arr.append("Fishall/Fish5_20.png")
        arr.append("Fishall/Fish5_21.png")
        arr.append("Fishall/Fish5_22.png")
        arr.append("Fishall/Fish5_23.png")
        arr.append("Fishall/Fish5_24.png")
        return arr
    }
    
    class func fish6() -> Array<String> {
        var arr = Array<String>()
        arr.append("Fishall/Fish6_1.png")
        arr.append("Fishall/Fish6_2.png")
        arr.append("Fishall/Fish6_3.png")
        arr.append("Fishall/Fish6_4.png")
        arr.append("Fishall/Fish6_5.png")
        arr.append("Fishall/Fish6_6.png")
        arr.append("Fishall/Fish6_7.png")
        arr.append("Fishall/Fish6_8.png")
        arr.append("Fishall/Fish6_9.png")
        arr.append("Fishall/Fish6_10.png")
        arr.append("Fishall/Fish6_11.png")
        arr.append("Fishall/Fish6_12.png")
        arr.append("Fishall/Fish6_13.png")
        arr.append("Fishall/Fish6_14.png")
        arr.append("Fishall/Fish6_15.png")
        arr.append("Fishall/Fish6_16.png")
        arr.append("Fishall/Fish6_17.png")
        arr.append("Fishall/Fish6_18.png")
        arr.append("Fishall/Fish6_19.png")
        arr.append("Fishall/Fish6_20.png")
        arr.append("Fishall/Fish6_21.png")
        arr.append("Fishall/Fish6_22.png")
        arr.append("Fishall/Fish6_23.png")
        arr.append("Fishall/Fish6_24.png")
        return arr
    }
    
    class func playerFish() -> Array<String> {
        var arr = Array<String>()
        arr.append("Fishall/playFish1.png")
        arr.append("Fishall/playFish2.png")
        arr.append("Fishall/playFish3.png")
        arr.append("Fishall/playFish4.png")
        arr.append("Fishall/playFish5.png")
        arr.append("Fishall/playFish6.png")
        arr.append("Fishall/playFish7.png")
        arr.append("Fishall/playFish8.png")
        arr.append("Fishall/playFish9.png")
        arr.append("Fishall/playFish10.png")
        arr.append("Fishall/playFish11.png")
        arr.append("Fishall/playFish12.png")
        arr.append("Fishall/playFish13.png")
        arr.append("Fishall/playFish14.png")
        arr.append("Fishall/playFish15.png")
        arr.append("Fishall/playFish16.png")
        arr.append("Fishall/playFish17.png")
        arr.append("Fishall/playFish18.png")
        arr.append("Fishall/playFish19.png")
        arr.append("Fishall/playFish20.png")
        arr.append("Fishall/playFish21.png")
        arr.append("Fishall/playFish22.png")
        arr.append("Fishall/playFish23.png")
        arr.append("Fishall/playFish24.png")
        return arr
    }
    
    class func playerBFish() -> Array<String> {
        var arr = Array<String>()
        arr.append("Fishall/playBFish1.png")
        arr.append("Fishall/playBFish2.png")
        arr.append("Fishall/playBFish3.png")
        arr.append("Fishall/playBFish4.png")
        arr.append("Fishall/playBFish5.png")
        arr.append("Fishall/playBFish6.png")
        arr.append("Fishall/playBFish7.png")
        arr.append("Fishall/playBFish8.png")
        arr.append("Fishall/playBFish9.png")
        arr.append("Fishall/playBFish10.png")
        arr.append("Fishall/playBFish11.png")
        arr.append("Fishall/playBFish12.png")
        arr.append("Fishall/playBFish13.png")
        arr.append("Fishall/playBFish14.png")
        arr.append("Fishall/playBFish15.png")
        arr.append("Fishall/playBFish16.png")
        arr.append("Fishall/playBFish17.png")
        arr.append("Fishall/playBFish18.png")
        arr.append("Fishall/playBFish19.png")
        arr.append("Fishall/playBFish20.png")
        arr.append("Fishall/playBFish21.png")
        arr.append("Fishall/playBFish22.png")
        arr.append("Fishall/playBFish23.png")
        arr.append("Fishall/playBFish24.png")
        return arr
    }
    
    class func playerMFish() -> Array<String> {
        var arr = Array<String>()
        arr.append("Fishall/playMFish1.png")
        arr.append("Fishall/playMFish2.png")
        arr.append("Fishall/playMFish3.png")
        arr.append("Fishall/playMFish4.png")
        arr.append("Fishall/playMFish5.png")
        arr.append("Fishall/playMFish6.png")
        arr.append("Fishall/playMFish7.png")
        arr.append("Fishall/playMFish8.png")
        arr.append("Fishall/playMFish9.png")
        arr.append("Fishall/playMFish10.png")
        arr.append("Fishall/playMFish11.png")
        arr.append("Fishall/playMFish12.png")
        arr.append("Fishall/playMFish13.png")
        arr.append("Fishall/playMFish14.png")
        arr.append("Fishall/playMFish15.png")
        arr.append("Fishall/playMFish16.png")
        arr.append("Fishall/playMFish17.png")
        arr.append("Fishall/playMFish18.png")
        arr.append("Fishall/playMFish19.png")
        arr.append("Fishall/playMFish20.png")
        arr.append("Fishall/playMFish21.png")
        arr.append("Fishall/playMFish22.png")
        arr.append("Fishall/playMFish23.png")
        arr.append("Fishall/playMFish24.png")
        return arr
    }
    
    class func jellyFish() -> Array<String> {
        var arr = Array<String>()
        arr.append("Fishtales/jellyfish1.png")
        arr.append("Fishtales/jellyfish2.png")
        arr.append("Fishtales/jellyfish3.png")
        arr.append("Fishtales/jellyfish4.png")
        arr.append("Fishtales/jellyfish5.png")
        arr.append("Fishtales/jellyfish6.png")
        arr.append("Fishtales/jellyfish7.png")
        arr.append("Fishtales/jellyfish8.png")
        arr.append("Fishtales/jellyfish9.png")
        arr.append("Fishtales/jellyfish10.png")
        arr.append("Fishtales/jellyfish11.png")
        arr.append("Fishtales/jellyfish12.png")
        arr.append("Fishtales/jellyfish13.png")
        arr.append("Fishtales/jellyfish14.png")
        arr.append("Fishtales/jellyfish15.png")
        arr.append("Fishtales/jellyfish16.png")
        arr.append("Fishtales/jellyfish17.png")
        arr.append("Fishtales/jellyfish18.png")
        arr.append("Fishtales/jellyfish19.png")
        arr.append("Fishtales/jellyfish20.png")
        arr.append("Fishtales/jellyfish21.png")
        arr.append("Fishtales/jellyfish22.png")
        arr.append("Fishtales/jellyfish23.png")
        arr.append("Fishtales/jellyfish24.png")
        return arr
    }
    
}
